apiVersion: apps/v1
kind: Deployment
meta
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    meta
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
